apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:4.1.13
        resources:
          limits:
            memory: 512Mi
            cpu: 80m
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
        volumeMounts:
        - name: mongo-db
          mountPath: /data/db
      volumes:
      - name: mongo-db
        persistentVolumeClaim:
          claimName: db