version: "2"
services:
  web:
    image: "node:10.16.0"
    volumes: ["./web/app:/app"]
    ports: ["3000:3000"]
    working_dir: "/app"
    # tty: true
    command: "yarn start"
    depends_on: ["mongo"]
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DB_NAME: customerdb
      MONGO_HOST: mongo
  mongo:
    image: "mongo:4.1.13"
    volumes: ["./db/data:/data/db"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  # mongo-express:
  #   image: "mongo-express"
  #   depends_on: ["mongo"]
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #   ports: ["8081:8081"]