apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: "web"
        image: "usalab/kube-app-demo-web:0.0.1"
        resources:
          limits:
            memory: "256Mi"
            cpu: "80m"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_USERNAME
          value: root
        - name: MONGO_PASSWORD
          value: root
        - name: MONGO_DB_NAME
          value: customerdb
        - name: MONGO_HOST
          value: db
        readinessProbe:
          httpGet:
            path: /
            port: 3000